# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu"
  config.vm.network :forwarded_port, guest: 9000, host: 9000
 
  config.vm.provision "shell", path: "script.sh"

end
